sudo: false
dist: trusty

language: d

os:
  - linux
  - osx

d:
  - dmd
  - dmd-beta
  - ldc
  - ldc-beta

env:
  - ARCH=x86_64 CONFIG=default
  - ARCH=x86_64 CONFIG=minimal
  - ARCH=x86_64 CONFIG=x11
  - ARCH=x86_64 CONFIG=console
  - ARCH=x86 CONFIG=default
  - ARCH=x86 CONFIG=minimal
  - ARCH=x86 CONFIG=x11
  - ARCH=x86 CONFIG=console

# No-one cares about OS X x86 and X11 on OSX
matrix:
  exclude:
    - os: osx
      env: ARCH=x86 CONFIG=default
    - os: osx
      env: ARCH=x86 CONFIG=minimal
    - os: osx
      env: ARCH=x86 CONFIG=x11
    - os: osx
      env: ARCH=x86_64 CONFIG=x11

addons:
  apt:
    packages:
      - gcc-multilib
      - libx11-dev
      - libx11-dev:i386
      - zlib1g-dev
      - zlib1g-dev:i386

script:
  - dub test --compiler=${DC} --arch=${ARCH} --config=${CONFIG}
  - dub build --compiler=${DC} --arch=${ARCH} --config=${CONFIG} :example1
  - file examples/example1/bin/example1
  - ls -lh examples/example1/bin/example1
  - strip examples/example1/bin/example1
  - ls -lh examples/example1/bin/example1
