language: d

os:
  - linux
  - osx

d:
  - dmd
  - dmd-beta
  - ldc
  - ldc-beta
  - gdc-6.3.0

env:
  - ARCH=x86_64 CONFIG=default
  - ARCH=x86_64 CONFIG=minimal
  - ARCH=x86_64 CONFIG=x11
  - ARCH=x86 CONFIG=default
  - ARCH=x86 CONFIG=minimal
  - ARCH=x86 CONFIG=x11

# No-one cares about OS X x86 and X11 on OSX
matrix:
  exclude:
    - os: osx
      env: ARCH=x86 CONFIG=default
    - os: osx
      env: ARCH=x86 CONFIG=minimal
    - os: osx
      env: ARCH=x86 CONFIG=x11
    - os: osx
      env: ARCH=x86_64 CONFIG=x11
    - os: osx
      d: gdc-6.3.0

sudo: true
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$ARCH" == "x86" ]]; then sudo apt-get install gcc-multilib; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CONFIG" == "x11" && "$ARCH" == "x86_64" ]]; then sudo apt-get install libx11-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CONFIG" == "x11" && "$ARCH" == "x86" ]]; then sudo apt-get install libx11-dev:i386; fi

script:
  - dub test --compiler=${DC} --arch=${ARCH} --config=${CONFIG}
  - dub build --compiler=${DC} --arch=${ARCH} --config=${CONFIG} :example1
  - file examples/example1/bin/example1
  - ls -lh examples/example1/bin/example1
  - strip examples/example1/bin/example1
  - ls -lh examples/example1/bin/example1
